version: '3.7'

services:
  postgres:
    image: 'postgres:14.0'
    container_name: 'postgres14_finance'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $HOME/Projects/Finance/postgresql-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    container_name: 'app_finance'
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/finance
      - gems:/gems

volumes:
  postgres:
  gems: